# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CLImageEditorDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CLImageEditorDemo

  pod 'CLImageEditor/AllTools', :git => 'https://github.com/ChronicStim/CLImageEditor.git', :branch => 'CPT_version_4_0_x', :inhibit_warnings => true

end
